-- Create sensor_data table
CREATE TABLE sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  beat_avg FLOAT,
  ir_value FLOAT,
  humidity FLOAT,
  temperature_c FLOAT,
  temperature_f FLOAT,
  heat_index_c FLOAT,
  heat_index_f FLOAT
);

-- Enable realtime for this table
ALTER PUBLICATION supabase_realtime ADD TABLE sensor_data;

-- Add RLS policies
ALTER TABLE sensor_data ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read sensor data
CREATE POLICY "Allow anyone to read sensor_data" ON sensor_data
  FOR SELECT USING (true);

-- Allow authenticated uploads from ESP8266
CREATE POLICY "Allow authenticated inserts to sensor_data" ON sensor_data
  FOR INSERT WITH CHECK (true); 

-- Verify the table exists and has the correct structure
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'sensor_data';

-- Verify the policies are in place
SELECT * FROM pg_policies 
WHERE tablename = 'sensor_data';